name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - 'orders/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker login -u kusamadocker -p $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS  }}
      - run: cd orders && docker build -t kusamadocker/micro-orders .
      - run: docker push kusamadocker/micro-orders
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save k8s-micro-ticket-cluster
      - run: kubectl rollout restart deployment orders-depl
