name: tests-payments

on:
  pull_request:
    paths:
      - 'payments/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: cd payments && npm install

      - name: Run tests
        run: npm run test:ci
        working-directory: ./payments
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
